-- MySQL Script generated by MySQL Workbench
-- Tue Feb  6 10:25:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cul_d_ampolla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cul_d_ampolla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cul_d_ampolla` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cul_d_ampolla` ;

-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(35) NOT NULL,
  `direccion_postal` VARCHAR(55) NOT NULL,
  `telefono` INT NOT NULL,
  `correo_electronico` VARCHAR(45) NOT NULL,
  `fecha_registro` DATE NOT NULL,
  `cliente_recomendado` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`colores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`colores` (
  `id_colores` INT NOT NULL AUTO_INCREMENT,
  `color_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_colores`),
  UNIQUE INDEX `idColores_UNIQUE` (`id_colores` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`montura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`montura` (
  `id_montura` INT NOT NULL AUTO_INCREMENT,
  `tipo_montura` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_montura`),
  UNIQUE INDEX `id_montura_UNIQUE` (`id_montura` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `NIF` VARCHAR(9) NOT NULL,
  `nombre` VARCHAR(35) NOT NULL,
  `telefono` VARCHAR(25) NOT NULL,
  `fax` VARCHAR(25) NOT NULL,
  `calle` VARCHAR(20) NULL DEFAULT NULL,
  `numero` INT NULL DEFAULT NULL,
  `piso` INT NULL DEFAULT NULL,
  `puerta` INT NULL DEFAULT NULL,
  `ciudad` VARCHAR(30) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `pais` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) VISIBLE,
  UNIQUE INDEX `proveedor_id_UNIQUE` (`id_proveedor` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`gafas` (
  `id_gafas` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(20) NOT NULL,
  `proveedor_id` INT NOT NULL,
  `id_montura` INT NOT NULL,
  `graduacion_lado_izq` FLOAT NULL DEFAULT NULL,
  `graduacion_lado_der` FLOAT NULL DEFAULT NULL,
  `color_vidrio` INT NULL DEFAULT NULL,
  `color_montura` INT NULL DEFAULT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`id_gafas`),
  UNIQUE INDEX `id_gafas_UNIQUE` (`id_gafas` ASC) VISIBLE,
  INDEX `fk_proveedor` (`proveedor_id` ASC) VISIBLE,
  INDEX `fk_montura_idx` (`id_montura` ASC) VISIBLE,
  INDEX `fk_color_vidrio_idx` (`color_vidrio` ASC) VISIBLE,
  INDEX `fk_color_montura_idx` (`color_montura` ASC) VISIBLE,
  CONSTRAINT `fk_color_montura`
    FOREIGN KEY (`color_montura`)
    REFERENCES `cul_d_ampolla`.`colores` (`id_colores`),
  CONSTRAINT `fk_color_vidrio`
    FOREIGN KEY (`color_vidrio`)
    REFERENCES `cul_d_ampolla`.`colores` (`id_colores`),
  CONSTRAINT `fk_montura`
    FOREIGN KEY (`id_montura`)
    REFERENCES `cul_d_ampolla`.`montura` (`id_montura`),
  CONSTRAINT `fk_proveedor`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `cul_d_ampolla`.`proveedor` (`id_proveedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`vendedor` (
  `id_vendedor` INT NOT NULL AUTO_INCREMENT,
  `nombre_vendedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_vendedor`),
  UNIQUE INDEX `id_vendedor_UNIQUE` (`id_vendedor` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cul_d_ampolla`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cul_d_ampolla`.`ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `gafas_id` INT NOT NULL,
  `vendedor_id` INT NOT NULL,
  `data_venta` DATE NOT NULL DEFAULT curdate(),
  PRIMARY KEY (`id_ventas`),
  UNIQUE INDEX `id_ventas_UNIQUE` (`id_ventas` ASC) VISIBLE,
  INDEX `gafas_id_idx` (`gafas_id` ASC) VISIBLE,
  INDEX `cliente_id_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `vendedor_id_idx` (`vendedor_id` ASC) VISIBLE,
  CONSTRAINT `cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `cul_d_ampolla`.`clientes` (`id_cliente`),
  CONSTRAINT `gafas_id`
    FOREIGN KEY (`gafas_id`)
    REFERENCES `cul_d_ampolla`.`gafas` (`id_gafas`),
  CONSTRAINT `vendedor_id`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `cul_d_ampolla`.`vendedor` (`id_vendedor`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
