
db.createCollection( 'glasses', {validator: {$jsonSchema: {bsonType: 'object',title:'glasses',required: [         'gafas',          'provedoor',          'ventas',          'ventas',          'ventas',          'ventas'],properties: {gafas: {bsonType: 'array',items: {
title:'object',required: [         'marca',          'graduacion',          'montura',          'color',          'precio'],properties: {marca: {bsonType: 'array',items: {bsonType: 'string'}},graduacion: {bsonType: 'object',
title:'object',required: [         'ojo_derecho',          'ojo_izquierdo'],properties: {ojo_derecho: {bsonType: 'decimal'},ojo_izquierdo: {bsonType: 'decimal'}}},montura: {bsonType: 'object',
title:'object',required: [         'flotante',          'pasta',          'metalica'],properties: {flotante: {bsonType: 'string'},pasta: {bsonType: 'string'},metalica: {bsonType: 'string'}}},color: {bsonType: 'array',items: {
title:'object',required: [         'color_montura',          'color_vidrio'],properties: {color_montura: {bsonType: 'string'},color_vidrio: {bsonType: 'object',
title:'object',required: [         'vidrio_derecho',          'vidrio_izquierdo'],properties: {vidrio_derecho: {bsonType: 'string'},vidrio_izquierdo: {bsonType: 'string'}}}}}},precio: {bsonType: 'decimal'}}}},provedoor: {bsonType: 'object',
title:'object',required: [         'nombre',          'direccion',          'telefono',          'fax',          'nif'],properties: {nombre: {bsonType: 'string'},direccion: {bsonType: 'array',items: {
title:'object',required: [         'calle',          'numero',          'piso',          'puerta',          'ciudad',          'codigo_postal',          'pais'],properties: {calle: {bsonType: 'string'},numero: {bsonType: 'int'},piso: {bsonType: 'int'},puerta: {bsonType: 'int'},ciudad: {bsonType: 'array',items: {bsonType: 'string'}},codigo_postal: {bsonType: 'array',items: {bsonType: 'int'}},pais: {bsonType: 'array',items: {bsonType: 'string'}}}}},telefono: {bsonType: 'array',items: {bsonType: 'int'}},fax: {bsonType: 'array',items: {bsonType: 'int'}},nif: {bsonType: 'array',items: {
title:'object',required: [         'numero_identificacion'],properties: {numero_identificacion: {bsonType: 'string'}}}}}},ventas: {bsonType: 'objectId'},ventas: {bsonType: 'array',items: {bsonType: 'string'}},ventas: {bsonType: 'array',items: {bsonType: 'objectId'}},ventas: {bsonType: 'array',items: {
title:'object',required: [         'fecha_venta',          'provedoor',          'cliente',          'empleado',          'cliente'],properties: {fecha_venta: {bsonType: 'date'},provedoor: {bsonType: 'objectId'},cliente: {bsonType: 'objectId'},empleado: {bsonType: 'array',items: {
title:'object',required: [         'nombre'],properties: {nombre: {bsonType: 'string'}}}},cliente: {bsonType: 'array',items: {
title:'object',required: [         'direccion',          'nombre',          'telefono',          'correo_electronico',          'fecha_registro',          'last_shopping'],properties: {direccion: {bsonType: 'string'},nombre: {bsonType: 'string'},telefono: {bsonType: 'array',items: {bsonType: 'int'}},correo_electronico: {bsonType: 'string'},fecha_registro: {bsonType: 'date'},last_shopping: {bsonType: 'object',
title:'object',required: [         'graduacion',          'glass_color',          'montura',          'precio'],properties: {graduacion: {bsonType: 'string'},glass_color: {bsonType: 'array',items: {bsonType: 'string'}},montura: {bsonType: 'array',items: {bsonType: 'string'}},precio: {bsonType: 'date'}}}}}}}}}}         }      }});  