-- MySQL Script generated by MySQL Workbench
-- Wed Feb  7 10:43:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzaria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pizzaria` ;

-- -----------------------------------------------------
-- Table `pizzaria`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`categorias` (
  `id_categorias` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categorias`),
  UNIQUE INDEX `id_categoria_pizza_UNIQUE` (`id_categorias` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`codigo-postal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`codigo-postal` (
  `id_codigo_postal` INT NOT NULL AUTO_INCREMENT,
  `codigo_postal` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_codigo_postal`),
  UNIQUE INDEX `id_codigo_postal_UNIQUE` (`id_codigo_postal` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`provincia` (
  `id_provincia` INT NOT NULL AUTO_INCREMENT,
  `nombre_provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_provincia`),
  UNIQUE INDEX `id_provincia_UNIQUE` (`id_provincia` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`localidad` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `provincia_id` INT NOT NULL,
  `codigo_postal_id` INT NOT NULL,
  `nombre_localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_localidad`),
  UNIQUE INDEX `id_localidad_UNIQUE` (`id_localidad` ASC) VISIBLE,
  INDEX `fk_provincia_idx` (`provincia_id` ASC) VISIBLE,
  INDEX `fk_codigo_postal_idx` (`codigo_postal_id` ASC) VISIBLE,
  CONSTRAINT `fk_codigo_postal`
    FOREIGN KEY (`codigo_postal_id`)
    REFERENCES `pizzaria`.`codigo-postal` (`id_codigo_postal`),
  CONSTRAINT `fk_provincia`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `pizzaria`.`provincia` (`id_provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NOT NULL,
  `apellido` VARCHAR(30) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `provincia_id` INT NOT NULL,
  `localidad_id` INT NOT NULL,
  `codigo_postal_id` INT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_localidad_idx` (`localidad_id` ASC) VISIBLE,
  INDEX `fk_provincia_idx` (`provincia_id` ASC) VISIBLE,
  INDEX `fk_provincias_idx` (`provincia_id` ASC) VISIBLE,
  INDEX `fk_codigo_postal__idx` (`codigo_postal_id` ASC) VISIBLE,
  CONSTRAINT `fk_codigo_postal_`
    FOREIGN KEY (`codigo_postal_id`)
    REFERENCES `pizzaria`.`codigo-postal` (`id_codigo_postal`),
  CONSTRAINT `fk_localidad`
    FOREIGN KEY (`localidad_id`)
    REFERENCES `pizzaria`.`localidad` (`id_localidad`),
  CONSTRAINT `fk_provincias`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `pizzaria`.`provincia` (`id_provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`puesto_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`puesto_laboral` (
  `id_puesto_laboral` INT NOT NULL AUTO_INCREMENT,
  `puesto_laboral` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_puesto_laboral`),
  UNIQUE INDEX `id_puesto_laboral_UNIQUE` (`id_puesto_laboral` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`tienda` (
  `id_tienda` INT NOT NULL AUTO_INCREMENT,
  `localidad_id` INT NOT NULL,
  `provincia_id` INT NOT NULL,
  `codigo-postal_id` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tienda`),
  UNIQUE INDEX `id_tienda_UNIQUE` (`id_tienda` ASC) VISIBLE,
  INDEX `fk_provincia_idx` (`provincia_id` ASC) VISIBLE,
  INDEX `fk_provincia_tienda_idx` (`provincia_id` ASC) VISIBLE,
  INDEX `fk_codigo_postal_tienda_idx` (`codigo-postal_id` ASC) VISIBLE,
  INDEX `fk_localidad_idx` (`localidad_id` ASC) VISIBLE,
  CONSTRAINT `fk_codigo_postal_tienda`
    FOREIGN KEY (`codigo-postal_id`)
    REFERENCES `pizzaria`.`codigo-postal` (`id_codigo_postal`),
  CONSTRAINT `fk_localidade_`
    FOREIGN KEY (`localidad_id`)
    REFERENCES `pizzaria`.`localidad` (`id_localidad`),
  CONSTRAINT `fk_provincia_tienda`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `pizzaria`.`provincia` (`id_provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `nif` VARCHAR(9) NOT NULL,
  `telefono` INT NOT NULL,
  `puesto_laboral_id` INT NOT NULL,
  `tienda_id` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX `id_empleado_UNIQUE` (`id_empleado` ASC) VISIBLE,
  INDEX `fk_puesto_laboral_idx` (`puesto_laboral_id` ASC) VISIBLE,
  INDEX `fk_puesto_idx` (`puesto_laboral_id` ASC) VISIBLE,
  INDEX `fk_tienda_idx` (`tienda_id` ASC) VISIBLE,
  CONSTRAINT `fk_puesto`
    FOREIGN KEY (`puesto_laboral_id`)
    REFERENCES `pizzaria`.`puesto_laboral` (`id_puesto_laboral`),
  CONSTRAINT `fk_tienda`
    FOREIGN KEY (`tienda_id`)
    REFERENCES `pizzaria`.`tienda` (`id_tienda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`reparto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`reparto` (
  `id_reparto` INT NOT NULL AUTO_INCREMENT,
  `empleado_id` INT NOT NULL,
  `tienda_id` INT NOT NULL,
  `fecha_hora` VARCHAR(45) NOT NULL DEFAULT 'now()',
  PRIMARY KEY (`id_reparto`),
  UNIQUE INDEX `id_reparto_UNIQUE` (`id_reparto` ASC) VISIBLE,
  INDEX `fk_empleado_idx` (`empleado_id` ASC) VISIBLE,
  INDEX `fk_tiendas_idx` (`tienda_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleado`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `pizzaria`.`empleado` (`id_empleado`),
  CONSTRAINT `fk_tiendas`
    FOREIGN KEY (`tienda_id`)
    REFERENCES `pizzaria`.`tienda` (`id_tienda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`tipo_envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`tipo_envio` (
  `id_tipo_envio` INT NOT NULL AUTO_INCREMENT,
  `tipo_envio` VARCHAR(20) NOT NULL,
  `tienda_id` INT NOT NULL,
  PRIMARY KEY (`id_tipo_envio`),
  UNIQUE INDEX `id_reparto_UNIQUE` (`id_tipo_envio` ASC) VISIBLE,
  INDEX `fk_tiendass_idx` (`tienda_id` ASC) VISIBLE,
  CONSTRAINT `fk_tiendass`
    FOREIGN KEY (`tienda_id`)
    REFERENCES `pizzaria`.`tienda` (`id_tienda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `tipo_envio_id` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `precio_total` FLOAT NOT NULL,
  `cantidad_producto_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `reparto_id` INT NOT NULL,
  `tienda_id` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  UNIQUE INDEX `id_pedido_UNIQUE` (`id_pedido` ASC) VISIBLE,
  INDEX `fk_tipo_envio_idx` (`tipo_envio_id` ASC) VISIBLE,
  INDEX `fk_cliente_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_repartos_idx` (`reparto_id` ASC) VISIBLE,
  INDEX `fk_tiends_idx` (`tienda_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `pizzaria`.`cliente` (`id_cliente`),
  CONSTRAINT `fk_repartos`
    FOREIGN KEY (`reparto_id`)
    REFERENCES `pizzaria`.`reparto` (`id_reparto`),
  CONSTRAINT `fk_tiends`
    FOREIGN KEY (`tienda_id`)
    REFERENCES `pizzaria`.`tienda` (`id_tienda`),
  CONSTRAINT `fk_tipo_envio`
    FOREIGN KEY (`tipo_envio_id`)
    REFERENCES `pizzaria`.`tipo_envio` (`id_tipo_envio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ruta_imagen` VARCHAR(1000) NOT NULL,
  `precio` FLOAT NOT NULL,
  `categoria_id` INT NOT NULL,
  `cantidad_producto` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  UNIQUE INDEX `id_producto_UNIQUE` (`id_producto` ASC) VISIBLE,
  INDEX `fk_categoria_pizza_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_pedidos_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_pizza`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `pizzaria`.`categorias` (`id_categorias`),
  CONSTRAINT `fk_pedidos`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `pizzaria`.`pedido` (`id_pedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizzaria`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzaria`.`pizza` (
  `id_pizza` INT NOT NULL AUTO_INCREMENT,
  `nombre_pizza` VARCHAR(45) NOT NULL,
  `categoria_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`id_pizza`),
  UNIQUE INDEX `id_pizza_UNIQUE` (`id_pizza` ASC) VISIBLE,
  INDEX `fk_categoria_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `fk_producto_idx` (`producto_id` ASC) VISIBLE,
  INDEX `fk_productos_idx` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `pizzaria`.`categorias` (`id_categorias`),
  CONSTRAINT `fk_productos`
    FOREIGN KEY (`producto_id`)
    REFERENCES `pizzaria`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
