use tienda;
SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SHOW COLUMNS FROM producto;
SELECT nombre, concat(precio, "€"), concat(precio, "$") FROM producto;
SELECT nombre AS NombreDeProducto, (precio) AS euros, (precio) AS dolares FROM producto;
select upper(nombre), precio FROM producto;
select lower(nombre), precio FROM producto;
select nombre, upper(substring(nombre, 1, 2)) FROM fabricante;
select nombre, round(precio, 1) FROM producto;
select nombre, truncate(precio, 0) FROM producto;
select fabricante.codigo FROM fabricante, producto where fabricante.codigo = producto.codigo_fabricante; 
select fabricante.codigo FROM fabricante, producto where fabricante.codigo = producto.codigo_fabricante group by fabricante.codigo;
select nombre From fabricante order by nombre ASC;
select nombre From fabricante order by nombre DESC;
select nombre, precio From producto order by nombre ASC, precio DESC;
select nombre from producto limit 5;
select nombre from producto limit 2 offset 3;
select nombre, precio from producto order by precio ASC limit 1;
select nombre, precio from producto order by precio DESC limit 1;
select nombre, codigo_fabricante from producto where codigo_fabricante = 2;
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo;
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo order by fabricante.nombre ASC;
select producto.nombre, producto.codigo, fabricante.nombre, fabricante.codigo from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo;
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo order by producto.precio ASC limit 1;
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo order by producto.precio DESC limit 1;
select producto.nombre, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = 'Lenovo';
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = 'Crucial' and producto.precio > 200;
select producto.nombre, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = 'Asus' or fabricante.nombre = 'Hewlett-Packard' or fabricante.nombre = 'Seagate';
select producto.nombre, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre in ('Asus', 'Hewlett-Packard', 'Seagate');
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre like '%e';
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre like '%w%';
select producto.nombre, producto.precio, fabricante.nombre from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where producto.precio >= 180 order by producto.precio DESC, producto.nombre ASC;
select fabricante.codigo, fabricante.nombre, producto.nombre from producto right join fabricante on producto.codigo_fabricante = fabricante.codigo order by fabricante.nombre;
select fabricante.codigo, fabricante.nombre, producto.nombre from producto right join fabricante on producto.codigo_fabricante = fabricante.codigo where isnull(producto.nombre);
select * from fabricante, producto where case fabricante.nombre when 'Lenovo' then true else false end;
-- select * from producto where exists (select * from producto where precio = producto.precio and codigo_fabricante != producto.codigo_fabricante and fabricante.nombre = 'Lenovo');
select fabricante.nombre, producto.precio from producto, fabricante where fabricante.nombre = 'Lenovo' order by precio Desc limit 1;
select fabricante.nombre, producto.precio from producto, fabricante where fabricante.nombre = 'Hewlett-Packard' order by precio ASC limit 1;
select producto.nombre, producto.precio from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where producto.precio >= (select max(producto.precio) from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = 'Lenovo');
select producto.nombre, producto.precio from producto inner join fabricante on producto.codigo_fabricante = fabricante.codigo where producto.precio >= (select avg(producto.precio) from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = 'Asus');
